### ISSUE TITLE
Example?

### ISSUE THREAD

**Issue by winkler1** [Theadd/react-panels#1]
Hi,
 Is there an online example for react.rocks? Was looking at it a few days ago, don't see it now. thanks.

**Comment by Theadd** [comment]
Thanks for telling me about react.rocks, I didn't know it. I've just submitted an example there, it's waiting for approval so it might become available at [http://react.rocks/example/react-panels](http://react.rocks/example/react-panels).

What you might have been looking at could be one of the following:
- react-panels [website](http://theadd.github.io/react-panels/), which has several examples.
- [http://react-components.com/component/react-panels](http://react-components.com/component/react-panels)
- [https://www.npmjs.com/package/react-panels](https://www.npmjs.com/package/react-panels)
- [http://bower.io/search/?q=react-panels](http://bower.io/search/?q=react-panels)

**Comment by Theadd** [comment]
Just checked, it's already available at [http://react.rocks/example/react-panels](http://react.rocks/example/react-panels).
