### ISSUE TITLE
Example of ResizableContent

### ISSUE THREAD

**Issue by yapcheahshen** [Theadd/react-panels#10]
Do we have example for ResizableContent in addons?

**Comment by yapcheahshen** [comment]
I miss understand the meaning of resize , it is for detecting if window get resized.
I am trying to have FloatingPanel which allow user to change width and height.

**Comment by Theadd** [comment]
Exactly, its for detecting if panel bounds get resized and not to allow the panel itself to be resizeable by mouse events.

``` jsx
... = React.createClass({
  ...

  handleResize: function (dimensions) {
    //console.dir(dimensions);
    this.refs.notifymeonresize.resize();
  },

  render: function () {
    ...
    return (
      ...
      <ResizableContent onResize={this.handleResize}>
        <SomeOtherComponent ref="notifymeonresize" />
      </ResizableContent>
      ...
    );
  }
});
```

I use this to resize [dygraph charts](http://dygraphs.com/) as they don't do it on their own.

Sorry for the delay.
