### ISSUE TITLE
z-order for floatingPanel

### ISSUE THREAD

**Issue by yapcheahshen** [Theadd/react-panels#16]
Please give me a guideline to implement z-order for floatingPanel,
which means click on floatingPanel caption or receive input focus bring it to front.

**Comment by Theadd** [comment]
Sure but give me a few hours, I'm a little bit busy right now =)

**Comment by Theadd** [comment]
Well, it might not be the best way of doing it but it's a fast solution.
replace the following highlighted lines of code ([2 lines](https://github.com/Theadd/react-panels/blob/master/src/jsx/panel.js#L97-L98)) with:

``` jsx
    return React.createElement("div", {style: wrapperStyle, onMouseDown: this.handleMouseDown}, this.inner);
  },

  handleMouseDown: function (e) {
    if (typeof this.props.onMouseDown === "function") {
      this.props.onMouseDown(e);
    }
  }
```

And [this is an example](https://gist.github.com/Theadd/e38c2308f097ef255046) using it.
