### ISSUE TITLE
Warning of changing props on React 0.13+

### ISSUE THREAD

**Issue by yapcheahshen** [Theadd/react-panels#2]
https://facebook.github.io/react/blog/2015/03/10/react-v0.13.html
"In this release, we've added runtime warnings that fire when props are changed or added between the time an element is created and when it's rendered"

Warning: Don't set .props._panelId of the React component <PanelButton />. Instead, specify the correct value when initially creating the element. The element was created by Panel.
react.js:19527 Warning: Don't set .props._active of the React component <PanelButton />. Instead, specify the correct value when initially creating the element. The element was created by Panel.
react.js:19527 Warning: Don't set .props._disabled of the React component <PanelButton />. Instead, specify the correct value when initially creating the element. The element was created by Panel.

**Comment by Theadd** [comment]
Yeah, I'm about to release _react-panels_ **v2** branch in the next hours (maybe tomorrow) which is entirely newly coded, using react v0.13.1 (backwards compatibility not tested yet). In v2 things are being done the way which react is meant to be used.

**Comment by yapcheahshen** [comment]
Great! thanks for your effort, it is an essential component of what I need exactly for a new project.
