### ISSUE TITLE
Examples cannot run with v2 and React 0.13.1

### ISSUE THREAD

**Issue by yapcheahshen** [Theadd/react-panels#3]
Warning: React.createElement: type should not be null or undefined. It should be a string (for DOM elements) or a ReactClass (for composite components).
react-with-addons.js:21560 Warning: Only functions or strings can be mounted as React components.

react-with-addons.js:9673 Uncaught TypeError: Cannot read property 'toUpperCase' of undefined

function autoGenerateWrapperClass(type) {
  return ReactClass.createClass({
    tagName: type.toUpperCase(),   <------ type is undefined
    render: function() {
....

**Comment by Theadd** [comment]
Wait, give me a couple of days. In some hours I'll commit an example but the ones made for prior versions are not compatible since its completely redesigned and not everything is implemented yet, like buttons.
