### ISSUE TITLE
compatible with commonjs 

### ISSUE THREAD

**Issue by yapcheahshen** [Theadd/react-panels#5]
Please consider to use commonjs (browserify, webpack)  format as many react component do.

**Comment by Theadd** [comment]
On my way =)

**Comment by Theadd** [comment]
Done. `npm install react-panels`

`var ReactPanels = require('react-panels')`
or
`var ReactPanels = require('react-panels/addons')`

No browserify/webpack bundle. To use it on the browser just do it like in the examples.

**Comment by Theadd** [comment]
Not tested but It shouldn't work. TODO: [canUseDom](https://github.com/kriasoft/react-starter-kit/blob/master/docs/react-style-guide.md#higher-order-react-component-example)
