### ISSUE TITLE
jsx file without jsx tag

### ISSUE THREAD

**Issue by yapcheahshen** [Theadd/react-panels#6]
some files, for example, base.jsx, buttons.jsx, utils.jsx has no jsx tag inside, please change it to .js .
it will be better if no jsx is used, so that pre-process of jsx tag can be removed.

**Comment by Theadd** [comment]
By the way, I would really appreciate some help from you or any other person that has something to contribute to this component, even themes, docs, example usages and of course, code improvements, bug fixes, new features, etc. So please feel free to make any pull request.

**Comment by Theadd** [comment]
Done, thanks.
